logfilepath: /var/log/cacher.log
datetimeformat: 2006-01-02 15:04:05
utctimeformat: 2006-01-02T15:04:05Z
scrapeinterval: 30
scrapeendpoint: /scraper/api/v1/scrape
expirythreshold: 70
retryinterval: 30